/**
 * Built-in Slack emoji shortcode → unicode map.
 *
 * Hand-curated to cover the high-frequency shortcodes that show up in
 * Slack message previews and reaction summaries. This is NOT a complete
 * unicode emoji set — we deliberately keep it small (~150 entries) so
 * the chunk weight stays trivial and the lookup is O(1) without pulling
 * in `node-emoji` or `emojibase`.
 *
 * Workspace custom emojis (the `:dosu-logo:` kind) override entries here
 * — see `useSlackEmojiMap` in `src/features/inbox/use-slack-emoji-map.ts`.
 *
 * Skin-tone variants (`:wave-skin-tone-3:`) fall back to the base name
 * via `stripSkinTone()` in `src/lib/slack-text.tsx`. We don't enumerate
 * per-tone unicode here (the table would explode for marginal value).
 */
export const BUILTIN_EMOJI: Record<string, string> = {
	// Reactions / agreement
	"+1": "👍",
	"-1": "👎",
	thumbsup: "👍",
	thumbsdown: "👎",
	ok_hand: "👌",
	clap: "👏",
	raised_hands: "🙌",
	heart_hands: "🫶",
	pray: "🙏",
	muscle: "💪",
	point_right: "👉",
	point_left: "👈",
	point_up: "👆",
	point_down: "👇",
	wave: "👋",
	call_me_hand: "🤙",
	writing_hand: "✍️",
	handshake: "🤝",
	crossed_fingers: "🤞",
	v: "✌️",
	salute: "🫡",

	// Faces — positive
	smile: "😄",
	smiley: "😃",
	grin: "😁",
	laughing: "😆",
	sweat_smile: "😅",
	joy: "😂",
	rofl: "🤣",
	rolling_on_the_floor_laughing: "🤣",
	relaxed: "☺️",
	blush: "😊",
	innocent: "😇",
	slightly_smiling_face: "🙂",
	upside_down_face: "🙃",
	wink: "😉",
	relieved: "😌",
	heart_eyes: "😍",
	smiling_face_with_3_hearts: "🥰",
	kissing_heart: "😘",
	yum: "😋",
	stuck_out_tongue: "😛",
	stuck_out_tongue_winking_eye: "😜",
	zany_face: "🤪",
	hugging_face: "🤗",
	star_struck: "🤩",
	partying_face: "🥳",
	"star-struck": "🤩",
	sunglasses: "😎",
	nerd_face: "🤓",
	thinking_face: "🤔",
	stuck_out_tongue_closed_eyes: "😝",
	face_with_monocle: "🧐",
	zipper_mouth_face: "🤐",
	shushing_face: "🤫",
	face_with_raised_eyebrow: "🤨",
	expressionless: "😑",
	neutral_face: "😐",

	// Faces — negative / dramatic
	sob: "😭",
	cry: "😢",
	disappointed: "😞",
	pensive: "😔",
	worried: "😟",
	confused: "😕",
	persevere: "😣",
	tired_face: "😫",
	weary: "😩",
	pleading_face: "🥺",
	face_holding_back_tears: "🥹",
	scream: "😱",
	fearful: "😨",
	cold_sweat: "😰",
	rage: "😡",
	angry: "😠",
	face_with_symbols_on_mouth: "🤬",
	exploding_head: "🤯",
	flushed: "😳",
	hot_face: "🥵",
	cold_face: "🥶",
	face_vomiting: "🤮",
	nauseated_face: "🤢",

	// Hearts / love
	heart: "❤️",
	red_heart: "❤️",
	orange_heart: "🧡",
	yellow_heart: "💛",
	green_heart: "💚",
	blue_heart: "💙",
	purple_heart: "💜",
	black_heart: "🖤",
	white_heart: "🤍",
	brown_heart: "🤎",
	sparkling_heart: "💖",
	two_hearts: "💕",
	heartbeat: "💓",
	cupid: "💘",

	// Signals / status
	"100": "💯",
	fire: "🔥",
	sparkles: "✨",
	star: "⭐",
	star2: "🌟",
	boom: "💥",
	zap: "⚡",
	dash: "💨",
	tada: "🎉",
	confetti_ball: "🎊",
	balloon: "🎈",
	bell: "🔔",
	mute: "🔇",
	loudspeaker: "📢",
	mega: "📣",
	rocket: "🚀",
	bulb: "💡",
	warning: "⚠️",
	question: "❓",
	exclamation: "❗",
	bangbang: "‼️",
	white_check_mark: "✅",
	heavy_check_mark: "✔️",
	x: "❌",
	negative_squared_cross_mark: "❎",
	no_entry: "⛔",
	no_entry_sign: "🚫",
	stop_sign: "🛑",
	eyes: "👀",
	speech_balloon: "💬",
	thought_balloon: "💭",
	zzz: "💤",

	// Objects / work
	pencil: "✏️",
	pencil2: "✏️",
	memo: "📝",
	bookmark: "🔖",
	mag: "🔍",
	mag_right: "🔎",
	hammer: "🔨",
	wrench: "🔧",
	hammer_and_wrench: "🛠️",
	gear: "⚙️",
	bug: "🐛",
	lock: "🔒",
	unlock: "🔓",
	key: "🔑",
	link: "🔗",
	paperclip: "📎",
	chart_with_upwards_trend: "📈",
	chart_with_downwards_trend: "📉",
	bar_chart: "📊",
	calendar: "📅",
	date: "📆",
	clock1: "🕐",
	hourglass_flowing_sand: "⏳",
	alarm_clock: "⏰",
	package: "📦",
	gift: "🎁",
	trophy: "🏆",
	medal: "🏅",
	first_place_medal: "🥇",
	second_place_medal: "🥈",
	third_place_medal: "🥉",

	// People / activities (often used as inline emoji like the golf-day
	// example in `:golfer:`)
	robot_face: "🤖",
	alien: "👽",
	ghost: "👻",
	skull: "💀",
	poop: "💩",
	clown_face: "🤡",
	golfer: "🏌️",
	man_golfing: "🏌️‍♂️",
	woman_golfing: "🏌️‍♀️",
	runner: "🏃",
	swimmer: "🏊",
	dancer: "💃",
	tophat: "🎩",
	crown: "👑",

	// Animals / nature (light coverage — these surface often as
	// reactions but aren't critical)
	dog: "🐶",
	cat: "🐱",
	mouse: "🐭",
	hamster: "🐹",
	rabbit: "🐰",
	bear: "🐻",
	panda_face: "🐼",
	koala: "🐨",
	tiger: "🐯",
	lion_face: "🦁",
	cow: "🐮",
	pig: "🐷",
	frog: "🐸",
	monkey_face: "🐵",
	chicken: "🐔",
	penguin: "🐧",
	bird: "🐦",
	unicorn_face: "🦄",
	sun_with_face: "🌞",
	sunny: "☀️",
	cloud: "☁️",
	umbrella_with_rain_drops: "☔",
	snowflake: "❄️",
	snowman: "⛄",

	// Food (very long tail in Slack; we cover the most common)
	pizza: "🍕",
	hamburger: "🍔",
	taco: "🌮",
	burrito: "🌯",
	coffee: "☕",
	tea: "🍵",
	beer: "🍺",
	beers: "🍻",
	wine_glass: "🍷",
	cocktail: "🍸",
	champagne: "🍾",
	cake: "🍰",
	birthday: "🎂",
	doughnut: "🍩",
	cookie: "🍪",
	apple: "🍎",
	banana: "🍌",
	hot_pepper: "🌶️",
	popcorn: "🍿",

	// Arrows / nav
	arrow_right: "➡️",
	arrow_left: "⬅️",
	arrow_up: "⬆️",
	arrow_down: "⬇️",
	arrow_upper_right: "↗️",
	arrow_lower_right: "↘️",
	arrow_upper_left: "↖️",
	arrow_lower_left: "↙️",
	leftwards_arrow_with_hook: "↩️",
	arrow_right_hook: "↪️",
	repeat: "🔁",
	twisted_rightwards_arrows: "🔀",
	back: "🔙",
};
