import fs from "node:fs";
import type { DevtaskPaths } from "./paths.js";

export interface DevtaskConfig {
  schemaVersion: 1;
  tracker: {
    provider: "jira" | null;
  };
  scm: {
    provider: "github" | "bitbucket" | "gitlab" | null;
  };
  agent: {
    provider: "codex" | "cursor";
  };
  agentSessions: {
    roots: {
      codex: string | null;
      cursor: string | null;
    };
  };
  codex: {
    model: string | null;
    fullAuto: boolean;
  };
  runtime: {
    mode: "attachable" | "plain";
    backend: "tmux" | null;
  };
  runtimeConfigured: boolean;
  jira: {
    baseUrl: string | null;
    email: string | null;
    cloudId: string | null;
  };
  verify: string[];
}

export const DEFAULT_CONFIG: DevtaskConfig = {
  schemaVersion: 1,
  tracker: {
    provider: null
  },
  scm: {
    provider: null
  },
  agent: {
    provider: "codex"
  },
  agentSessions: {
    roots: {
      codex: null,
      cursor: null
    }
  },
  codex: {
    model: null,
    fullAuto: true
  },
  runtime: {
    mode: "attachable",
    backend: "tmux"
  },
  runtimeConfigured: false,
  jira: {
    baseUrl: null,
    email: null,
    cloudId: null
  },
  verify: []
};

export function readConfig(paths: DevtaskPaths): DevtaskConfig {
  if (!fs.existsSync(paths.configPath)) {
    return DEFAULT_CONFIG;
  }

  const value = JSON.parse(fs.readFileSync(paths.configPath, "utf8")) as Partial<DevtaskConfig>;
  const jira = parseJiraConfig(value.jira);
  return {
    schemaVersion: 1,
    tracker: parseTrackerConfig(value.tracker, jira),
    scm: parseScmConfig(value.scm),
    agent: parseAgentConfig(value.agent),
    agentSessions: parseAgentSessionsConfig(value.agentSessions),
    codex: {
      model: typeof value.codex?.model === "string" ? value.codex.model : null,
      fullAuto: typeof value.codex?.fullAuto === "boolean" ? value.codex.fullAuto : true
    },
    runtime: parseRuntimeConfig(value.runtime),
    runtimeConfigured: value.runtimeConfigured === true,
    jira,
    verify: Array.isArray(value.verify) ? value.verify.filter((item): item is string => typeof item === "string") : []
  };
}

function parseAgentConfig(value: unknown): DevtaskConfig["agent"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.agent;
  }

  const record = value as { provider?: unknown };
  return {
    provider: record.provider === "cursor" ? "cursor" : "codex"
  };
}

function parseAgentSessionsConfig(value: unknown): DevtaskConfig["agentSessions"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.agentSessions;
  }

  const record = value as { roots?: unknown };
  if (typeof record.roots !== "object" || record.roots === null || Array.isArray(record.roots)) {
    return DEFAULT_CONFIG.agentSessions;
  }

  const roots = record.roots as { codex?: unknown; cursor?: unknown };
  return {
    roots: {
      codex: typeof roots.codex === "string" && roots.codex.trim() ? roots.codex.trim() : null,
      cursor: typeof roots.cursor === "string" && roots.cursor.trim() ? roots.cursor.trim() : null
    }
  };
}

export function hasRuntimeConfig(paths: DevtaskPaths): boolean {
  if (!fs.existsSync(paths.configPath)) {
    return false;
  }

  try {
    const value = JSON.parse(fs.readFileSync(paths.configPath, "utf8")) as { runtime?: unknown; runtimeConfigured?: unknown };
    if (typeof value.runtime !== "object" || value.runtime === null || Array.isArray(value.runtime)) {
      return false;
    }
    const runtime = value.runtime as { mode?: unknown; backend?: unknown };
    if (value.runtimeConfigured === true) {
      return (runtime.mode === "attachable" && runtime.backend === "tmux") || (runtime.mode === "plain" && runtime.backend === null);
    }

    // Backward compatibility: old attachable configs were always user-visible choices.
    // Plain configs without this marker may have been generated by initializeStore.
    return runtime.mode === "attachable" && runtime.backend === "tmux";
  } catch {
    return false;
  }
}

export function writeConfig(paths: DevtaskPaths, config: DevtaskConfig): void {
  fs.mkdirSync(paths.baseDir, { recursive: true });
  fs.writeFileSync(paths.configPath, `${JSON.stringify(config, null, 2)}\n`);
}

function parseRuntimeConfig(value: unknown): DevtaskConfig["runtime"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.runtime;
  }

  const record = value as { mode?: unknown; backend?: unknown };
  if (record.mode === "attachable" && record.backend === "tmux") {
    return {
      mode: "attachable",
      backend: "tmux"
    };
  }

  return {
    mode: "plain",
    backend: null
  };
}

function parseTrackerConfig(value: unknown, jira: DevtaskConfig["jira"]): DevtaskConfig["tracker"] {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    const record = value as { provider?: unknown };
    return {
      provider: record.provider === "jira" ? "jira" : null
    };
  }

  return {
    provider: jira.baseUrl || jira.email || jira.cloudId ? "jira" : null
  };
}

function parseScmConfig(value: unknown): DevtaskConfig["scm"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.scm;
  }

  const record = value as { provider?: unknown };
  return {
    provider:
      record.provider === "github" || record.provider === "bitbucket" || record.provider === "gitlab"
        ? record.provider
        : null
  };
}

function parseJiraConfig(value: unknown): DevtaskConfig["jira"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.jira;
  }

  const record = value as { baseUrl?: unknown; email?: unknown; cloudId?: unknown };
  return {
    baseUrl: typeof record.baseUrl === "string" && record.baseUrl.trim() ? record.baseUrl.trim().replace(/\/+$/, "") : null,
    email: typeof record.email === "string" && record.email.trim() ? record.email.trim() : null,
    cloudId: typeof record.cloudId === "string" && record.cloudId.trim() ? record.cloudId.trim() : null
  };
}
