import fs from "node:fs";
import type { DevtaskPaths } from "./paths.js";

export interface DevtaskConfig {
  schemaVersion: 1;
  codex: {
    model: string | null;
    fullAuto: boolean;
  };
  runtime: {
    mode: "attachable" | "plain";
    backend: "tmux" | null;
  };
  runtimeConfigured: boolean;
  jira: {
    baseUrl: string | null;
    email: string | null;
    cloudId: string | null;
  };
  verify: string[];
}

export const DEFAULT_CONFIG: DevtaskConfig = {
  schemaVersion: 1,
  codex: {
    model: null,
    fullAuto: true
  },
  runtime: {
    mode: "attachable",
    backend: "tmux"
  },
  runtimeConfigured: false,
  jira: {
    baseUrl: null,
    email: null,
    cloudId: null
  },
  verify: []
};

export function readConfig(paths: DevtaskPaths): DevtaskConfig {
  if (!fs.existsSync(paths.configPath)) {
    return DEFAULT_CONFIG;
  }

  const value = JSON.parse(fs.readFileSync(paths.configPath, "utf8")) as Partial<DevtaskConfig>;
  return {
    schemaVersion: 1,
    codex: {
      model: typeof value.codex?.model === "string" ? value.codex.model : null,
      fullAuto: typeof value.codex?.fullAuto === "boolean" ? value.codex.fullAuto : true
    },
    runtime: parseRuntimeConfig(value.runtime),
    runtimeConfigured: value.runtimeConfigured === true,
    jira: parseJiraConfig(value.jira),
    verify: Array.isArray(value.verify) ? value.verify.filter((item): item is string => typeof item === "string") : []
  };
}

export function hasRuntimeConfig(paths: DevtaskPaths): boolean {
  if (!fs.existsSync(paths.configPath)) {
    return false;
  }

  try {
    const value = JSON.parse(fs.readFileSync(paths.configPath, "utf8")) as { runtime?: unknown; runtimeConfigured?: unknown };
    if (typeof value.runtime !== "object" || value.runtime === null || Array.isArray(value.runtime)) {
      return false;
    }
    const runtime = value.runtime as { mode?: unknown; backend?: unknown };
    if (value.runtimeConfigured === true) {
      return (runtime.mode === "attachable" && runtime.backend === "tmux") || (runtime.mode === "plain" && runtime.backend === null);
    }

    // Backward compatibility: old attachable configs were always user-visible choices.
    // Plain configs without this marker may have been generated by initializeStore.
    return runtime.mode === "attachable" && runtime.backend === "tmux";
  } catch {
    return false;
  }
}

export function writeConfig(paths: DevtaskPaths, config: DevtaskConfig): void {
  fs.mkdirSync(paths.baseDir, { recursive: true });
  fs.writeFileSync(paths.configPath, `${JSON.stringify(config, null, 2)}\n`);
}

export function buildCodexCommand(
  options: { model?: string | null; fullAuto?: boolean; skipGitRepoCheck?: boolean; addDirs?: string[] } = {}
): string {
  const args = ["codex", "exec"];
  if (options.fullAuto !== false) {
    args.push("--full-auto");
  }
  if (options.skipGitRepoCheck) {
    args.push("--skip-git-repo-check");
  }
  args.push("--add-dir", '"$DEVTASK_TASK_DIR"');
  for (const dir of options.addDirs ?? []) {
    args.push("--add-dir", shellQuote(dir));
  }
  if (options.model) {
    args.push("-m", shellQuote(options.model));
  }
  args.push("-", "<", '"$DEVTASK_TASK_PATH"');
  return args.join(" ");
}

function shellQuote(value: string): string {
  if (/^[A-Za-z0-9._/:@+-]+$/.test(value)) {
    return value;
  }

  return `'${value.replaceAll("'", "'\\''")}'`;
}

function parseRuntimeConfig(value: unknown): DevtaskConfig["runtime"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.runtime;
  }

  const record = value as { mode?: unknown; backend?: unknown };
  if (record.mode === "attachable" && record.backend === "tmux") {
    return {
      mode: "attachable",
      backend: "tmux"
    };
  }

  return {
    mode: "plain",
    backend: null
  };
}

function parseJiraConfig(value: unknown): DevtaskConfig["jira"] {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return DEFAULT_CONFIG.jira;
  }

  const record = value as { baseUrl?: unknown; email?: unknown; cloudId?: unknown };
  return {
    baseUrl: typeof record.baseUrl === "string" && record.baseUrl.trim() ? record.baseUrl.trim().replace(/\/+$/, "") : null,
    email: typeof record.email === "string" && record.email.trim() ? record.email.trim() : null,
    cloudId: typeof record.cloudId === "string" && record.cloudId.trim() ? record.cloudId.trim() : null
  };
}
