import type { WorkItem } from "../storage/work-store.js";

export function buildOrchestratorPrompt(
  item: WorkItem,
  specPath: string,
  contractPath: string,
  planPath: string,
  graphPath: string,
  workId: string
): string {
  return [
    `Orchestrate work item ${workId}.`,
    "",
    "You are the devtask orchestrator. Your job is to produce four planning artifacts and then spawn per-repo planning workers.",
    "Do not modify source code, run tests, or mutate git state.",
    "",
    "Source:",
    `- type: ${item.source.type}`,
    `- title: ${item.source.title}`,
    `- artifact: ${item.source.artifact}`,
    ...("url" in item.source ? [`- url: ${item.source.url}`] : []),
    "",
    "--- Step 1: Write the spec ---",
    "",
    `Write the spec to: ${specPath}`,
    "",
    "Spec sections:",
    "1. Summary",
    "2. Problem Statement",
    "3. In Scope",
    "4. Out of Scope",
    "5. Functional Requirements",
    "6. Acceptance Criteria",
    "7. Constraints and Assumptions",
    "8. Open Questions",
    "",
    "Rules:",
    "- Clarify the request into a concise, implementation-ready spec.",
    "- Ground everything in the source artifact.",
    "- Make assumptions explicit instead of hiding them.",
    "- If the ticket is vague, capture the ambiguity under Open Questions.",
    "- Do not include code changes or a repo execution graph.",
    "",
    "--- Step 2: Write the validation contract ---",
    "",
    `Write the validation contract to: ${contractPath}`,
    "",
    "Rules:",
    "- Write one assertion per line in the format: VAL-001: <behavioral description>",
    "- Each assertion must describe an observable outcome: an HTTP status, a stored value, a UI state, a data change.",
    "- Derive assertions directly from the Acceptance Criteria in the spec.",
    "- Do not describe implementation details (no 'calls Redis', no 'runs middleware').",
    "- Number sequentially: VAL-001, VAL-002, ...",
    "- Do not write assertions for items captured under Open Questions.",
    "",
    "--- Step 3: Write the plan and graph ---",
    "",
    `Write the human-readable plan to: ${planPath}`,
    `Write the machine-readable graph JSON to: ${graphPath}`,
    "",
    "Plan sections:",
    "1. Summary",
    "2. Source Inputs",
    "3. Affected Repos",
    "4. Proposed Execution Graph",
    "5. Ownership Boundaries",
    "6. Dependencies",
    "7. Validation Plan",
    "8. Risks and Open Questions",
    "",
    "Graph JSON schema:",
    "",
    "```json",
    "{",
    '  "schemaVersion": 1,',
    `  "workId": "${workId}",`,
    '  "tasks": [',
    "    {",
    '      "id": "short-task-id",',
    '      "repoId": "workspace-repo-id",',
    '      "goal": "repo/scope-local goal",',
    '      "owns": ["path/or/scope/**"],',
    '      "dependencies": [',
    "        {",
    '          "task": "other-task-id",',
    '          "type": "run|review|validation",',
    '          "reason": "why this dependency exists"',
    "        }",
    "      ]",
    "    }",
    "  ],",
    '  "validation": ["check command or validation responsibility"],',
    '  "openQuestions": []',
    "}",
    "```",
    "",
    "Rules:",
    "- Use only repos you discover in the workspace; do not invent repo IDs.",
    "- If no repo clearly applies, output an empty tasks array and explain under openQuestions.",
    "- Prefer explicit ownership boundaries over broad repo-level ownership.",
    "- Prefer parallel execution unless there is a concrete dependency blocker.",
    "- The graph file must contain JSON only, with no Markdown fences.",
    "",
    "--- Step 4: Spawn repo-plan workers ---",
    "",
    "After writing graph.json, read the tasks array. For each task, spawn a headless repo-plan worker:",
    "",
    "  devtask work _repo-plan-worker --work-id WORK_ID --repo-id REPO_ID",
    "",
    "Run workers in parallel using shell background jobs, then wait:",
    "",
    "  devtask work _repo-plan-worker --work-id WORK_ID --repo-id backend &",
    "  devtask work _repo-plan-worker --work-id WORK_ID --repo-id frontend &",
    "  wait",
    "",
    "Replace WORK_ID and REPO_ID with the actual values from graph.json.",
    "A non-zero exit code from a worker means that repo-plan failed — note it but do not stop other workers.",
    "If graph.json has no tasks, skip this step."
  ].join("\n");
}
