import type { TaskMeta } from "../types.js";

export function buildRepoPlanPrompt(
  meta: Pick<TaskMeta, "id">,
  writablePlanPath: string,
  finalPlanPath: string,
  task: string,
  state: string,
  memory = ""
): string {
  return [
    `Plan task ${meta.id}.`,
    "",
    "You are in the devtask planning stage.",
    "",
    "Task:",
    "",
    task || "(task file is empty)",
    "",
    "Current state:",
    "",
    state || "(state file is empty)",
    "",
    "Goal:",
    "Create an implementation plan only. Do not modify source code, tests, docs, config, package files, generated files, git state, or any other repository file.",
    `The only file you may write is this worktree-local devtask plan artifact: ${writablePlanPath}.`,
    `Devtask will persist that plan to: ${finalPlanPath}.`,
    "Do not update task state during planning, even if the task instructions mention state updates.",
    "",
    "Before writing the plan:",
    "- Inspect the repository structure.",
    "- Read the task and current state.",
    "- Read relevant files needed to understand existing patterns.",
    "- Prefer local conventions over new abstractions.",
    "- Do not invent requirements that are not present in the task.",
    "",
    "Write the plan with these Markdown sections:",
    "1. Summary",
    "2. Task Inputs",
    "3. Relevant Existing Files",
    "4. Current Behavior / Current Structure",
    "5. Proposed Changes",
    "6. Step-by-Step Implementation Plan",
    "7. Tests / Checks",
    "8. Risks and Assumptions",
    "9. Out of Scope",
    "10. Open Questions or Blockers",
    "",
    "Planning rules:",
    "- Every implementation step must name the expected files, modules, or areas it will touch.",
    "- Mark assumptions explicitly.",
    "- Keep the plan scoped to the task goal.",
    "- Do not include code patches unless a small interface sketch is necessary to remove ambiguity.",
    "- Make the plan precise enough that another agent can implement it without re-discovering the whole task.",
    "",
    ...(memory ? [memory, ""] : []),
    "If the task is blocked, write a short blocked plan and set $DEVTASK_RESULT_PATH to {\"status\":\"blocked\",\"reason\":\"...\"}.",
    "Otherwise, leave $DEVTASK_RESULT_PATH unchanged and ensure the plan file is complete."
  ].join("\n");
}
